title: 简历 - Java 开发工程师 - 汤晔飞

aboutme:
  name: 汤晔飞
  sex: 男
  age: 29
  email: 584856024@qq.com
  phone: 18917058261
  github: https://github.com/aner1001
  blog: https://aner1001.github.io/
  blog2: https://aner1001.gitee.io/
  city: 上海市嘉定区
  job: Java开发工程师
  edu: 本科
  native: 上海
  school: 上海海事大学
  major: 计算机科学与技术
  workingyear: 6年
  qq: 584856024


update: 2022年7月20日
